---
jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: git-concourse-build-docker-image
    trigger: true
  - put: docker-image
    params:
      build: git-concourse-build-docker-image/

resources:
- name: git-concourse-build-docker-image
  type: git
  source:
    uri:  https://github.com/kondurupurandhar/aqasec-poc
    branch: master

- name: docker-image
  type: docker-image
  source:
    email: https://hub.docker.com
    username: purandhar
    password: password-1
    repository: purandhar/aqua
